### ISSUE TITLE
Run all servers with 1 command vs individually

### ISSUE THREAD

**Issue by known-blue** [UofI-CDACS/fanuc_ros2_drivers#2]
Currently its set up that you have to start each action server individually. We should add a script that can run all of these servers with 1 command.

**Comment by JamesL-dev** [comment]
A launch file would do this for us,  plus a lot of other cool stuff. Eventually a bunch of these actions will be grouped into one node. We are currently discussing how to organize the architecture.

**Comment by known-blue** [comment]
Fixed with launch file in newest version of Dev branch
